name: "External Action"
description: "This is the action that is called by wg-process workflow"
inputs:
  input3:
    description: "An example input"
    required: true
  input4:
    description: "Another example input"
    required: false
runs:
  using: "composite"
  steps:
    - name: Echo Merge to Next Branch
      run: |
      echo "Merge to next branch"

    - name: Run Command
      run: |
        echo "Running external action from wg-tools"
        echo "Received inputs: ${{ inputs.input3 }}, ${{ inputs.input4 }}"
      shell: bash
